# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pixel-city' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pixel-city
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'

  pod 'Fabric'
  pod 'Crashlytics'

  # iPad mini / iPhoneX detection
  pod 'Device', '~> 3.0.0'

  #most widely-used auto-layout engine for ios
  pod 'SnapKit', '~> 4.0.0' 
  pod 'Material'
  pod 'CocoaLumberjack'
  pod 'XLPagerTabStrip'
  pod 'Unbox'
  pod 'UnboxedAlamofire'
  pod 'SDWebImage'
  pod 'CocoaLumberjack'
  pod 'LumberjackConsole'

end
